### ISSUE TITLE
Documents aren't displaying

### ISSUE THREAD

**Issue by magicspon** [Q42/sanity-plugin-page-tree#2]
https://github.com/Q42/sanity-plugin-page-tree/assets/3268717/4ad580c8-c137-4aa2-9634-a83bdd7ff565

Bit of a weird one... Pretty sure I've followed the instructions correctly.  Any ideas?

repo https://github.com/magicspon/sanity-tree-issue

**Comment by djohalo2** [comment]
@magicspon Can you update the plugin to version `1.0.3` and try again?

**Comment by magicspon** [comment]
![PixelSnap 2023-12-20 at 14 12 24](https://github.com/Q42/sanity-plugin-page-tree/assets/3268717/0d685618-21fa-4e6f-888f-f7f34275b57c)

huzzah! 

is it possible to rearrange the items?
